version: v2.12.2
plugins:
  - module: 'github.com/stackitcloud/terraform-provider-stackit/tools'
    import: 'github.com/stackitcloud/terraform-provider-stackit/tools/linters/tfacl'
    path: ./tools
  - module: 'github.com/stackitcloud/terraform-provider-stackit/tools'
    import: 'github.com/stackitcloud/terraform-provider-stackit/tools/linters/tfctxinit'
    path: ./tools
  - module: 'github.com/stackitcloud/terraform-provider-stackit/tools'
    import: 'github.com/stackitcloud/terraform-provider-stackit/tools/linters/tflogresponse'
    path: ./tools
