version: v2.12.2
plugins:
  - module: 'github.com/stackitcloud/terraform-provider-stackit/tools'
    import: 'github.com/stackitcloud/terraform-provider-stackit/tools/linters/pkgstutter'
    path: ./tools
