trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  # Definir variables globales para usarlas en los scripts
  # NOTA: En ADO, la autenticación OIDC funciona diferente a GitHub.
  # Es posible que necesites una Service Connection o configurar las credenciales explícitamente.
  STACKIT_USE_OIDC: "1"
  STACKIT_SERVICE_ACCOUNT_EMAIL: "test-idp-njf5pc1@sa.stackit.cloud"
  # Versión de Go (ajusta según tu go.mod)
  GO_VERSION: "1.22"

jobs:
  - job: Build_and_Test
    displayName: "Build Provider & Test Plan"

    steps:
      - checkout: self

      - script: |
          echo "SYSTEM_OIDCREQUESTURI: $(SYSTEM_OIDCREQUESTURI)"
          echo "SYSTEM_ACCESSTOKEN: $(SYSTEM_ACCESSTOKEN)"
          echo "System.OidcRequestUri: $(System.OidcRequestUri)"
          echo "System.AccessToken: $(System.AccessToken)"

        displayName: "Check Environment"
      # 1. Instalar Go
      - task: GoTool@0
        inputs:
          version: "$(GO_VERSION)"
        displayName: "Setup Go"

      # 2. Compilar el Provider
      - script: |
          go build -o terraform-provider-stackit
          chmod +x terraform-provider-stackit

          # En ADO usamos $(Build.SourcesDirectory) en lugar de GITHUB_WORKSPACE
          echo "##vso[task.setvariable variable=BINARY_PATH]$(Build.SourcesDirectory)"
        displayName: "Build Provider"

      # 3. Configurar Overrides de Terraform
      - script: |
          cat <<EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "stackitcloud/stackit" = "$(BINARY_PATH)"
            }
            # Para otros providers (random, null, etc), usa el registro normal
            direct {}
          }
          EOF

          echo "Terraform RC content:"
          cat ~/.terraformrc
        displayName: "Configure Terraform Dev Overrides"

      # 4. Instalar Terraform
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: "latest"
        displayName: "Setup Terraform"

      # 5. Crear configuración de prueba (main.tf)
      - script: |
          cat <<EOF > main.tf
          terraform {
            required_providers {
              stackit = {
                source = "stackitcloud/stackit"
              }
            }
          }

          provider "stackit" {
            default_region                       = "eu01"
            enable_beta_resources                = true
            service_account_custom_endpoint      = "https://service-account.api.qa.stackit.cloud"
            token_custom_endpoint                = "https://accounts.qa.stackit.cloud/oauth/v2/token"
          }

          resource "stackit_service_account" "sa"   {
            project_id = "62675838-7758-4b99-a4eb-84b20ac8626b"
            name       = "terraform-wif-ci"
          }
          EOF
        displayName: "Create Test Configuration"

      # 6. Terraform Plan
      - script: |
          terraform init -backend=false
          terraform plan -out=tfplan
        displayName: "Terraform Plan"
        env:
          STACKIT_USE_OIDC: $(STACKIT_USE_OIDC)
          STACKIT_SERVICE_ACCOUNT_EMAIL: $(STACKIT_SERVICE_ACCOUNT_EMAIL)

      # 7. Terraform Apply
      - script: |
          terraform apply -auto-approve tfplan
        displayName: "Terraform Apply"
        env:
          STACKIT_USE_OIDC: $(STACKIT_USE_OIDC)
          STACKIT_SERVICE_ACCOUNT_EMAIL: $(STACKIT_SERVICE_ACCOUNT_EMAIL)

      # 8. Terraform Destroy (Siempre se ejecuta)
      - script: |
          if [ -f terraform.tfstate ]; then
            terraform destroy -auto-approve
          else
            echo "No state file found, skipping destroy."
          fi
        displayName: "Terraform Destroy"
        condition: always() # Equivalente a if: always() en GitHub Actions
        env:
          STACKIT_USE_OIDC: $(STACKIT_USE_OIDC)
          STACKIT_SERVICE_ACCOUNT_EMAIL: $(STACKIT_SERVICE_ACCOUNT_EMAIL)
