/*
STACKIT MSSQL Service API

This is the documentation for the STACKIT MSSQL service

API version: 3alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sqlserverflexalpha

import (
	"encoding/json"
)

// checks if the ResetUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetUserResponse{}

/*
	types and functions for password
*/

// isNotNullableString
type ResetUserResponseGetPasswordAttributeType = *string

func getResetUserResponseGetPasswordAttributeTypeOk(arg ResetUserResponseGetPasswordAttributeType) (ret ResetUserResponseGetPasswordRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setResetUserResponseGetPasswordAttributeType(arg *ResetUserResponseGetPasswordAttributeType, val ResetUserResponseGetPasswordRetType) {
	*arg = &val
}

type ResetUserResponseGetPasswordArgType = string
type ResetUserResponseGetPasswordRetType = string

/*
	types and functions for status
*/

// isNotNullableString
type ResetUserResponseGetStatusAttributeType = *string

func getResetUserResponseGetStatusAttributeTypeOk(arg ResetUserResponseGetStatusAttributeType) (ret ResetUserResponseGetStatusRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setResetUserResponseGetStatusAttributeType(arg *ResetUserResponseGetStatusAttributeType, val ResetUserResponseGetStatusRetType) {
	*arg = &val
}

type ResetUserResponseGetStatusArgType = string
type ResetUserResponseGetStatusRetType = string

/*
	types and functions for uri
*/

// isNotNullableString
type ResetUserResponseGetUriAttributeType = *string

func getResetUserResponseGetUriAttributeTypeOk(arg ResetUserResponseGetUriAttributeType) (ret ResetUserResponseGetUriRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setResetUserResponseGetUriAttributeType(arg *ResetUserResponseGetUriAttributeType, val ResetUserResponseGetUriRetType) {
	*arg = &val
}

type ResetUserResponseGetUriArgType = string
type ResetUserResponseGetUriRetType = string

/*
	types and functions for username
*/

// isNotNullableString
type ResetUserResponseGetUsernameAttributeType = *string

func getResetUserResponseGetUsernameAttributeTypeOk(arg ResetUserResponseGetUsernameAttributeType) (ret ResetUserResponseGetUsernameRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setResetUserResponseGetUsernameAttributeType(arg *ResetUserResponseGetUsernameAttributeType, val ResetUserResponseGetUsernameRetType) {
	*arg = &val
}

type ResetUserResponseGetUsernameArgType = string
type ResetUserResponseGetUsernameRetType = string

// ResetUserResponse struct for ResetUserResponse
type ResetUserResponse struct {
	// The password for the user.
	// REQUIRED
	Password ResetUserResponseGetPasswordAttributeType `json:"password" required:"true"`
	// The current status of the user.
	// REQUIRED
	Status ResetUserResponseGetStatusAttributeType `json:"status" required:"true"`
	// The connection string for the user to the instance.
	// REQUIRED
	Uri ResetUserResponseGetUriAttributeType `json:"uri" required:"true"`
	// The name of the user.
	// REQUIRED
	Username ResetUserResponseGetUsernameAttributeType `json:"username" required:"true"`
}

type _ResetUserResponse ResetUserResponse

// NewResetUserResponse instantiates a new ResetUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetUserResponse(password ResetUserResponseGetPasswordArgType, status ResetUserResponseGetStatusArgType, uri ResetUserResponseGetUriArgType, username ResetUserResponseGetUsernameArgType) *ResetUserResponse {
	this := ResetUserResponse{}
	setResetUserResponseGetPasswordAttributeType(&this.Password, password)
	setResetUserResponseGetStatusAttributeType(&this.Status, status)
	setResetUserResponseGetUriAttributeType(&this.Uri, uri)
	setResetUserResponseGetUsernameAttributeType(&this.Username, username)
	return &this
}

// NewResetUserResponseWithDefaults instantiates a new ResetUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetUserResponseWithDefaults() *ResetUserResponse {
	this := ResetUserResponse{}
	return &this
}

// GetPassword returns the Password field value
func (o *ResetUserResponse) GetPassword() (ret ResetUserResponseGetPasswordRetType) {
	ret, _ = o.GetPasswordOk()
	return ret
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ResetUserResponse) GetPasswordOk() (ret ResetUserResponseGetPasswordRetType, ok bool) {
	return getResetUserResponseGetPasswordAttributeTypeOk(o.Password)
}

// SetPassword sets field value
func (o *ResetUserResponse) SetPassword(v ResetUserResponseGetPasswordRetType) {
	setResetUserResponseGetPasswordAttributeType(&o.Password, v)
}

// GetStatus returns the Status field value
func (o *ResetUserResponse) GetStatus() (ret ResetUserResponseGetStatusRetType) {
	ret, _ = o.GetStatusOk()
	return ret
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ResetUserResponse) GetStatusOk() (ret ResetUserResponseGetStatusRetType, ok bool) {
	return getResetUserResponseGetStatusAttributeTypeOk(o.Status)
}

// SetStatus sets field value
func (o *ResetUserResponse) SetStatus(v ResetUserResponseGetStatusRetType) {
	setResetUserResponseGetStatusAttributeType(&o.Status, v)
}

// GetUri returns the Uri field value
func (o *ResetUserResponse) GetUri() (ret ResetUserResponseGetUriRetType) {
	ret, _ = o.GetUriOk()
	return ret
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *ResetUserResponse) GetUriOk() (ret ResetUserResponseGetUriRetType, ok bool) {
	return getResetUserResponseGetUriAttributeTypeOk(o.Uri)
}

// SetUri sets field value
func (o *ResetUserResponse) SetUri(v ResetUserResponseGetUriRetType) {
	setResetUserResponseGetUriAttributeType(&o.Uri, v)
}

// GetUsername returns the Username field value
func (o *ResetUserResponse) GetUsername() (ret ResetUserResponseGetUsernameRetType) {
	ret, _ = o.GetUsernameOk()
	return ret
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ResetUserResponse) GetUsernameOk() (ret ResetUserResponseGetUsernameRetType, ok bool) {
	return getResetUserResponseGetUsernameAttributeTypeOk(o.Username)
}

// SetUsername sets field value
func (o *ResetUserResponse) SetUsername(v ResetUserResponseGetUsernameRetType) {
	setResetUserResponseGetUsernameAttributeType(&o.Username, v)
}

func (o ResetUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getResetUserResponseGetPasswordAttributeTypeOk(o.Password); ok {
		toSerialize["Password"] = val
	}
	if val, ok := getResetUserResponseGetStatusAttributeTypeOk(o.Status); ok {
		toSerialize["Status"] = val
	}
	if val, ok := getResetUserResponseGetUriAttributeTypeOk(o.Uri); ok {
		toSerialize["Uri"] = val
	}
	if val, ok := getResetUserResponseGetUsernameAttributeTypeOk(o.Username); ok {
		toSerialize["Username"] = val
	}
	return toSerialize, nil
}

type NullableResetUserResponse struct {
	value *ResetUserResponse
	isSet bool
}

func (v NullableResetUserResponse) Get() *ResetUserResponse {
	return v.value
}

func (v *NullableResetUserResponse) Set(val *ResetUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResetUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResetUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetUserResponse(val *ResetUserResponse) *NullableResetUserResponse {
	return &NullableResetUserResponse{value: val, isSet: true}
}

func (v NullableResetUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
