/*
STACKIT VPN API

The STACKIT VPN API provides endpoints to provision and manage VPN instances in your STACKIT project.

API version: 1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vpnalpha

import (
	"encoding/json"
)

// checks if the CreateVPNGatewayPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVPNGatewayPayload{}

/*
	types and functions for availabilityZones
*/

// isModel
type CreateVPNGatewayPayloadGetAvailabilityZonesAttributeType = *CreateVPNGatewayPayloadAvailabilityZones
type CreateVPNGatewayPayloadGetAvailabilityZonesArgType = CreateVPNGatewayPayloadAvailabilityZones
type CreateVPNGatewayPayloadGetAvailabilityZonesRetType = CreateVPNGatewayPayloadAvailabilityZones

func getCreateVPNGatewayPayloadGetAvailabilityZonesAttributeTypeOk(arg CreateVPNGatewayPayloadGetAvailabilityZonesAttributeType) (ret CreateVPNGatewayPayloadGetAvailabilityZonesRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateVPNGatewayPayloadGetAvailabilityZonesAttributeType(arg *CreateVPNGatewayPayloadGetAvailabilityZonesAttributeType, val CreateVPNGatewayPayloadGetAvailabilityZonesRetType) {
	*arg = &val
}

/*
	types and functions for bgpEnabled
*/

// isBoolean
type CreateVPNGatewayPayloadgetBgpEnabledAttributeType = *bool
type CreateVPNGatewayPayloadgetBgpEnabledArgType = bool
type CreateVPNGatewayPayloadgetBgpEnabledRetType = bool

func getCreateVPNGatewayPayloadgetBgpEnabledAttributeTypeOk(arg CreateVPNGatewayPayloadgetBgpEnabledAttributeType) (ret CreateVPNGatewayPayloadgetBgpEnabledRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateVPNGatewayPayloadgetBgpEnabledAttributeType(arg *CreateVPNGatewayPayloadgetBgpEnabledAttributeType, val CreateVPNGatewayPayloadgetBgpEnabledRetType) {
	*arg = &val
}

/*
	types and functions for bgpGatewayConfig
*/

// isModel
type CreateVPNGatewayPayloadGetBgpGatewayConfigAttributeType = *BGPGatewayConfig
type CreateVPNGatewayPayloadGetBgpGatewayConfigArgType = BGPGatewayConfig
type CreateVPNGatewayPayloadGetBgpGatewayConfigRetType = BGPGatewayConfig

func getCreateVPNGatewayPayloadGetBgpGatewayConfigAttributeTypeOk(arg CreateVPNGatewayPayloadGetBgpGatewayConfigAttributeType) (ret CreateVPNGatewayPayloadGetBgpGatewayConfigRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateVPNGatewayPayloadGetBgpGatewayConfigAttributeType(arg *CreateVPNGatewayPayloadGetBgpGatewayConfigAttributeType, val CreateVPNGatewayPayloadGetBgpGatewayConfigRetType) {
	*arg = &val
}

/*
	types and functions for labels
*/

// isContainer
type CreateVPNGatewayPayloadGetLabelsAttributeType = *map[string]string
type CreateVPNGatewayPayloadGetLabelsArgType = map[string]string
type CreateVPNGatewayPayloadGetLabelsRetType = map[string]string

func getCreateVPNGatewayPayloadGetLabelsAttributeTypeOk(arg CreateVPNGatewayPayloadGetLabelsAttributeType) (ret CreateVPNGatewayPayloadGetLabelsRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateVPNGatewayPayloadGetLabelsAttributeType(arg *CreateVPNGatewayPayloadGetLabelsAttributeType, val CreateVPNGatewayPayloadGetLabelsRetType) {
	*arg = &val
}

/*
	types and functions for name
*/

// isNotNullableString
type CreateVPNGatewayPayloadGetNameAttributeType = *string

func getCreateVPNGatewayPayloadGetNameAttributeTypeOk(arg CreateVPNGatewayPayloadGetNameAttributeType) (ret CreateVPNGatewayPayloadGetNameRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateVPNGatewayPayloadGetNameAttributeType(arg *CreateVPNGatewayPayloadGetNameAttributeType, val CreateVPNGatewayPayloadGetNameRetType) {
	*arg = &val
}

type CreateVPNGatewayPayloadGetNameArgType = string
type CreateVPNGatewayPayloadGetNameRetType = string

/*
	types and functions for planId
*/

// isNotNullableString
type CreateVPNGatewayPayloadGetPlanIdAttributeType = *string

func getCreateVPNGatewayPayloadGetPlanIdAttributeTypeOk(arg CreateVPNGatewayPayloadGetPlanIdAttributeType) (ret CreateVPNGatewayPayloadGetPlanIdRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateVPNGatewayPayloadGetPlanIdAttributeType(arg *CreateVPNGatewayPayloadGetPlanIdAttributeType, val CreateVPNGatewayPayloadGetPlanIdRetType) {
	*arg = &val
}

type CreateVPNGatewayPayloadGetPlanIdArgType = string
type CreateVPNGatewayPayloadGetPlanIdRetType = string

// CreateVPNGatewayPayload struct for CreateVPNGatewayPayload
type CreateVPNGatewayPayload struct {
	// REQUIRED
	AvailabilityZones CreateVPNGatewayPayloadGetAvailabilityZonesAttributeType `json:"availabilityZones" required:"true"`
	// Enable BGP routing. (This will require a BGPGatewayConfig and also a BGPTunnelConfig for each Tunnel in each Connection)
	BgpEnabled       CreateVPNGatewayPayloadgetBgpEnabledAttributeType       `json:"bgpEnabled,omitempty"`
	BgpGatewayConfig CreateVPNGatewayPayloadGetBgpGatewayConfigAttributeType `json:"bgpGatewayConfig,omitempty"`
	// Map of custom labels. Key and values must be max 63 chars, start/end with alphanumeric.
	Labels CreateVPNGatewayPayloadGetLabelsAttributeType `json:"labels,omitempty"`
	// The name of the VPN gateway.  Maximum 20 characters (only alphanumeric and hyphens allowed). Not changeable after creation.
	// REQUIRED
	Name CreateVPNGatewayPayloadGetNameAttributeType `json:"name" required:"true"`
	// Service Plan to configure the limits of the VPN. Currently supported plans are p50, p100, p200. This list can change in the future where plan ids will be removed and new plans by added. That is the reason this is not an enum.
	// REQUIRED
	PlanId CreateVPNGatewayPayloadGetPlanIdAttributeType `json:"planId" required:"true"`
}

type _CreateVPNGatewayPayload CreateVPNGatewayPayload

// NewCreateVPNGatewayPayload instantiates a new CreateVPNGatewayPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVPNGatewayPayload(availabilityZones CreateVPNGatewayPayloadGetAvailabilityZonesArgType, name CreateVPNGatewayPayloadGetNameArgType, planId CreateVPNGatewayPayloadGetPlanIdArgType) *CreateVPNGatewayPayload {
	this := CreateVPNGatewayPayload{}
	setCreateVPNGatewayPayloadGetAvailabilityZonesAttributeType(&this.AvailabilityZones, availabilityZones)
	setCreateVPNGatewayPayloadGetNameAttributeType(&this.Name, name)
	setCreateVPNGatewayPayloadGetPlanIdAttributeType(&this.PlanId, planId)
	return &this
}

// NewCreateVPNGatewayPayloadWithDefaults instantiates a new CreateVPNGatewayPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVPNGatewayPayloadWithDefaults() *CreateVPNGatewayPayload {
	this := CreateVPNGatewayPayload{}
	return &this
}

// GetAvailabilityZones returns the AvailabilityZones field value
func (o *CreateVPNGatewayPayload) GetAvailabilityZones() (ret CreateVPNGatewayPayloadGetAvailabilityZonesRetType) {
	ret, _ = o.GetAvailabilityZonesOk()
	return ret
}

// GetAvailabilityZonesOk returns a tuple with the AvailabilityZones field value
// and a boolean to check if the value has been set.
func (o *CreateVPNGatewayPayload) GetAvailabilityZonesOk() (ret CreateVPNGatewayPayloadGetAvailabilityZonesRetType, ok bool) {
	return getCreateVPNGatewayPayloadGetAvailabilityZonesAttributeTypeOk(o.AvailabilityZones)
}

// SetAvailabilityZones sets field value
func (o *CreateVPNGatewayPayload) SetAvailabilityZones(v CreateVPNGatewayPayloadGetAvailabilityZonesRetType) {
	setCreateVPNGatewayPayloadGetAvailabilityZonesAttributeType(&o.AvailabilityZones, v)
}

// GetBgpEnabled returns the BgpEnabled field value if set, zero value otherwise.
func (o *CreateVPNGatewayPayload) GetBgpEnabled() (res CreateVPNGatewayPayloadgetBgpEnabledRetType) {
	res, _ = o.GetBgpEnabledOk()
	return
}

// GetBgpEnabledOk returns a tuple with the BgpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVPNGatewayPayload) GetBgpEnabledOk() (ret CreateVPNGatewayPayloadgetBgpEnabledRetType, ok bool) {
	return getCreateVPNGatewayPayloadgetBgpEnabledAttributeTypeOk(o.BgpEnabled)
}

// HasBgpEnabled returns a boolean if a field has been set.
func (o *CreateVPNGatewayPayload) HasBgpEnabled() bool {
	_, ok := o.GetBgpEnabledOk()
	return ok
}

// SetBgpEnabled gets a reference to the given bool and assigns it to the BgpEnabled field.
func (o *CreateVPNGatewayPayload) SetBgpEnabled(v CreateVPNGatewayPayloadgetBgpEnabledRetType) {
	setCreateVPNGatewayPayloadgetBgpEnabledAttributeType(&o.BgpEnabled, v)
}

// GetBgpGatewayConfig returns the BgpGatewayConfig field value if set, zero value otherwise.
func (o *CreateVPNGatewayPayload) GetBgpGatewayConfig() (res CreateVPNGatewayPayloadGetBgpGatewayConfigRetType) {
	res, _ = o.GetBgpGatewayConfigOk()
	return
}

// GetBgpGatewayConfigOk returns a tuple with the BgpGatewayConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVPNGatewayPayload) GetBgpGatewayConfigOk() (ret CreateVPNGatewayPayloadGetBgpGatewayConfigRetType, ok bool) {
	return getCreateVPNGatewayPayloadGetBgpGatewayConfigAttributeTypeOk(o.BgpGatewayConfig)
}

// HasBgpGatewayConfig returns a boolean if a field has been set.
func (o *CreateVPNGatewayPayload) HasBgpGatewayConfig() bool {
	_, ok := o.GetBgpGatewayConfigOk()
	return ok
}

// SetBgpGatewayConfig gets a reference to the given BGPGatewayConfig and assigns it to the BgpGatewayConfig field.
func (o *CreateVPNGatewayPayload) SetBgpGatewayConfig(v CreateVPNGatewayPayloadGetBgpGatewayConfigRetType) {
	setCreateVPNGatewayPayloadGetBgpGatewayConfigAttributeType(&o.BgpGatewayConfig, v)
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateVPNGatewayPayload) GetLabels() (res CreateVPNGatewayPayloadGetLabelsRetType) {
	res, _ = o.GetLabelsOk()
	return
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVPNGatewayPayload) GetLabelsOk() (ret CreateVPNGatewayPayloadGetLabelsRetType, ok bool) {
	return getCreateVPNGatewayPayloadGetLabelsAttributeTypeOk(o.Labels)
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateVPNGatewayPayload) HasLabels() bool {
	_, ok := o.GetLabelsOk()
	return ok
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateVPNGatewayPayload) SetLabels(v CreateVPNGatewayPayloadGetLabelsRetType) {
	setCreateVPNGatewayPayloadGetLabelsAttributeType(&o.Labels, v)
}

// GetName returns the Name field value
func (o *CreateVPNGatewayPayload) GetName() (ret CreateVPNGatewayPayloadGetNameRetType) {
	ret, _ = o.GetNameOk()
	return ret
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateVPNGatewayPayload) GetNameOk() (ret CreateVPNGatewayPayloadGetNameRetType, ok bool) {
	return getCreateVPNGatewayPayloadGetNameAttributeTypeOk(o.Name)
}

// SetName sets field value
func (o *CreateVPNGatewayPayload) SetName(v CreateVPNGatewayPayloadGetNameRetType) {
	setCreateVPNGatewayPayloadGetNameAttributeType(&o.Name, v)
}

// GetPlanId returns the PlanId field value
func (o *CreateVPNGatewayPayload) GetPlanId() (ret CreateVPNGatewayPayloadGetPlanIdRetType) {
	ret, _ = o.GetPlanIdOk()
	return ret
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *CreateVPNGatewayPayload) GetPlanIdOk() (ret CreateVPNGatewayPayloadGetPlanIdRetType, ok bool) {
	return getCreateVPNGatewayPayloadGetPlanIdAttributeTypeOk(o.PlanId)
}

// SetPlanId sets field value
func (o *CreateVPNGatewayPayload) SetPlanId(v CreateVPNGatewayPayloadGetPlanIdRetType) {
	setCreateVPNGatewayPayloadGetPlanIdAttributeType(&o.PlanId, v)
}

func (o CreateVPNGatewayPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getCreateVPNGatewayPayloadGetAvailabilityZonesAttributeTypeOk(o.AvailabilityZones); ok {
		toSerialize["AvailabilityZones"] = val
	}
	if val, ok := getCreateVPNGatewayPayloadgetBgpEnabledAttributeTypeOk(o.BgpEnabled); ok {
		toSerialize["BgpEnabled"] = val
	}
	if val, ok := getCreateVPNGatewayPayloadGetBgpGatewayConfigAttributeTypeOk(o.BgpGatewayConfig); ok {
		toSerialize["BgpGatewayConfig"] = val
	}
	if val, ok := getCreateVPNGatewayPayloadGetLabelsAttributeTypeOk(o.Labels); ok {
		toSerialize["Labels"] = val
	}
	if val, ok := getCreateVPNGatewayPayloadGetNameAttributeTypeOk(o.Name); ok {
		toSerialize["Name"] = val
	}
	if val, ok := getCreateVPNGatewayPayloadGetPlanIdAttributeTypeOk(o.PlanId); ok {
		toSerialize["PlanId"] = val
	}
	return toSerialize, nil
}

type NullableCreateVPNGatewayPayload struct {
	value *CreateVPNGatewayPayload
	isSet bool
}

func (v NullableCreateVPNGatewayPayload) Get() *CreateVPNGatewayPayload {
	return v.value
}

func (v *NullableCreateVPNGatewayPayload) Set(val *CreateVPNGatewayPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVPNGatewayPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVPNGatewayPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVPNGatewayPayload(val *CreateVPNGatewayPayload) *NullableCreateVPNGatewayPayload {
	return &NullableCreateVPNGatewayPayload{value: val, isSet: true}
}

func (v NullableCreateVPNGatewayPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVPNGatewayPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
