// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package postgresflexalpha

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connection_string": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection string for the user to the instance.",
				MarkdownDescription: "The connection string for the user to the instance.",
			},
			"host": schema.StringAttribute{
				Computed:            true,
				Description:         "The host of the instance in which the user belongs to.",
				MarkdownDescription: "The host of the instance in which the user belongs to.",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the user.",
				MarkdownDescription: "The ID of the user.",
			},
			"instance_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the instance.",
				MarkdownDescription: "The ID of the instance.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the user.",
				MarkdownDescription: "The name of the user.",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "The port of the instance in which the user belongs to.",
				MarkdownDescription: "The port of the instance in which the user belongs to.",
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				Description:         "The STACKIT project ID.",
				MarkdownDescription: "The STACKIT project ID.",
			},
			"region": schema.StringAttribute{
				Required:            true,
				Description:         "The region which should be addressed",
				MarkdownDescription: "The region which should be addressed",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"eu01",
					),
				},
			},
			"roles": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "A list of user roles.",
				MarkdownDescription: "A list of user roles.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The current status of the user.",
				MarkdownDescription: "The current status of the user.",
			},
			"user_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the user.",
				MarkdownDescription: "The ID of the user.",
			},
		},
	}
}

type UserModel struct {
	ConnectionString types.String `tfsdk:"connection_string"`
	Host             types.String `tfsdk:"host"`
	Id               types.Int64  `tfsdk:"id"`
	InstanceId       types.String `tfsdk:"instance_id"`
	Name             types.String `tfsdk:"name"`
	Port             types.Int64  `tfsdk:"port"`
	ProjectId        types.String `tfsdk:"project_id"`
	Region           types.String `tfsdk:"region"`
	Roles            types.List   `tfsdk:"roles"`
	Status           types.String `tfsdk:"status"`
	UserId           types.Int64  `tfsdk:"user_id"`
}
