/*
STACKIT IaaS API

This API allows you to create and modify IaaS resources.

API version: 2beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iaasbeta

import (
	"encoding/json"
)

// checks if the AffinityGroupListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffinityGroupListResponse{}

/*
	types and functions for items
*/

// isArray
type AffinityGroupListResponseGetItemsAttributeType = *[]AffinityGroup
type AffinityGroupListResponseGetItemsArgType = []AffinityGroup
type AffinityGroupListResponseGetItemsRetType = []AffinityGroup

func getAffinityGroupListResponseGetItemsAttributeTypeOk(arg AffinityGroupListResponseGetItemsAttributeType) (ret AffinityGroupListResponseGetItemsRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setAffinityGroupListResponseGetItemsAttributeType(arg *AffinityGroupListResponseGetItemsAttributeType, val AffinityGroupListResponseGetItemsRetType) {
	*arg = &val
}

// AffinityGroupListResponse Response object for affinity group list request.
type AffinityGroupListResponse struct {
	// A list of affinity groups.
	// REQUIRED
	Items AffinityGroupListResponseGetItemsAttributeType `json:"items" required:"true"`
}

type _AffinityGroupListResponse AffinityGroupListResponse

// NewAffinityGroupListResponse instantiates a new AffinityGroupListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffinityGroupListResponse(items AffinityGroupListResponseGetItemsArgType) *AffinityGroupListResponse {
	this := AffinityGroupListResponse{}
	setAffinityGroupListResponseGetItemsAttributeType(&this.Items, items)
	return &this
}

// NewAffinityGroupListResponseWithDefaults instantiates a new AffinityGroupListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffinityGroupListResponseWithDefaults() *AffinityGroupListResponse {
	this := AffinityGroupListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *AffinityGroupListResponse) GetItems() (ret AffinityGroupListResponseGetItemsRetType) {
	ret, _ = o.GetItemsOk()
	return ret
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AffinityGroupListResponse) GetItemsOk() (ret AffinityGroupListResponseGetItemsRetType, ok bool) {
	return getAffinityGroupListResponseGetItemsAttributeTypeOk(o.Items)
}

// SetItems sets field value
func (o *AffinityGroupListResponse) SetItems(v AffinityGroupListResponseGetItemsRetType) {
	setAffinityGroupListResponseGetItemsAttributeType(&o.Items, v)
}

func (o AffinityGroupListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getAffinityGroupListResponseGetItemsAttributeTypeOk(o.Items); ok {
		toSerialize["Items"] = val
	}
	return toSerialize, nil
}

type NullableAffinityGroupListResponse struct {
	value *AffinityGroupListResponse
	isSet bool
}

func (v NullableAffinityGroupListResponse) Get() *AffinityGroupListResponse {
	return v.value
}

func (v *NullableAffinityGroupListResponse) Set(val *AffinityGroupListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAffinityGroupListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAffinityGroupListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffinityGroupListResponse(val *AffinityGroupListResponse) *NullableAffinityGroupListResponse {
	return &NullableAffinityGroupListResponse{value: val, isSet: true}
}

func (v NullableAffinityGroupListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffinityGroupListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
