/*
PostgreSQL Flex API

This is the documentation for the STACKIT Postgres Flex service

API version: 3alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postgresflexalpha

import (
	"encoding/json"
)

// checks if the ProtectInstanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtectInstanceResponse{}

/*
	types and functions for isDeletable
*/

// isBoolean
type ProtectInstanceResponsegetIsDeletableAttributeType = *bool
type ProtectInstanceResponsegetIsDeletableArgType = bool
type ProtectInstanceResponsegetIsDeletableRetType = bool

func getProtectInstanceResponsegetIsDeletableAttributeTypeOk(arg ProtectInstanceResponsegetIsDeletableAttributeType) (ret ProtectInstanceResponsegetIsDeletableRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setProtectInstanceResponsegetIsDeletableAttributeType(arg *ProtectInstanceResponsegetIsDeletableAttributeType, val ProtectInstanceResponsegetIsDeletableRetType) {
	*arg = &val
}

// ProtectInstanceResponse struct for ProtectInstanceResponse
type ProtectInstanceResponse struct {
	// Protect instance from deletion.
	// REQUIRED
	IsDeletable ProtectInstanceResponsegetIsDeletableAttributeType `json:"isDeletable" required:"true"`
}

type _ProtectInstanceResponse ProtectInstanceResponse

// NewProtectInstanceResponse instantiates a new ProtectInstanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectInstanceResponse(isDeletable ProtectInstanceResponsegetIsDeletableArgType) *ProtectInstanceResponse {
	this := ProtectInstanceResponse{}
	setProtectInstanceResponsegetIsDeletableAttributeType(&this.IsDeletable, isDeletable)
	return &this
}

// NewProtectInstanceResponseWithDefaults instantiates a new ProtectInstanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectInstanceResponseWithDefaults() *ProtectInstanceResponse {
	this := ProtectInstanceResponse{}
	return &this
}

// GetIsDeletable returns the IsDeletable field value
func (o *ProtectInstanceResponse) GetIsDeletable() (ret ProtectInstanceResponsegetIsDeletableRetType) {
	ret, _ = o.GetIsDeletableOk()
	return ret
}

// GetIsDeletableOk returns a tuple with the IsDeletable field value
// and a boolean to check if the value has been set.
func (o *ProtectInstanceResponse) GetIsDeletableOk() (ret ProtectInstanceResponsegetIsDeletableRetType, ok bool) {
	return getProtectInstanceResponsegetIsDeletableAttributeTypeOk(o.IsDeletable)
}

// SetIsDeletable sets field value
func (o *ProtectInstanceResponse) SetIsDeletable(v ProtectInstanceResponsegetIsDeletableRetType) {
	setProtectInstanceResponsegetIsDeletableAttributeType(&o.IsDeletable, v)
}

func (o ProtectInstanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getProtectInstanceResponsegetIsDeletableAttributeTypeOk(o.IsDeletable); ok {
		toSerialize["IsDeletable"] = val
	}
	return toSerialize, nil
}

type NullableProtectInstanceResponse struct {
	value *ProtectInstanceResponse
	isSet bool
}

func (v NullableProtectInstanceResponse) Get() *ProtectInstanceResponse {
	return v.value
}

func (v *NullableProtectInstanceResponse) Set(val *ProtectInstanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectInstanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectInstanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectInstanceResponse(val *ProtectInstanceResponse) *NullableProtectInstanceResponse {
	return &NullableProtectInstanceResponse{value: val, isSet: true}
}

func (v NullableProtectInstanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectInstanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
