/*
PostgreSQL Flex API

This is the documentation for the STACKIT Postgres Flex service

API version: 3alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postgresflexalpha
