/*
STACKIT File Storage (SFS)

API used to create and manage NFS Shares.

API version: 1beta.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfsbeta

import (
	"encoding/json"
)

// checks if the ValidationErrorField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorField{}

/*
	types and functions for field
*/

// isNotNullableString
type ValidationErrorFieldGetFieldAttributeType = *string

func getValidationErrorFieldGetFieldAttributeTypeOk(arg ValidationErrorFieldGetFieldAttributeType) (ret ValidationErrorFieldGetFieldRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setValidationErrorFieldGetFieldAttributeType(arg *ValidationErrorFieldGetFieldAttributeType, val ValidationErrorFieldGetFieldRetType) {
	*arg = &val
}

type ValidationErrorFieldGetFieldArgType = string
type ValidationErrorFieldGetFieldRetType = string

/*
	types and functions for reason
*/

// isNotNullableString
type ValidationErrorFieldGetReasonAttributeType = *string

func getValidationErrorFieldGetReasonAttributeTypeOk(arg ValidationErrorFieldGetReasonAttributeType) (ret ValidationErrorFieldGetReasonRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setValidationErrorFieldGetReasonAttributeType(arg *ValidationErrorFieldGetReasonAttributeType, val ValidationErrorFieldGetReasonRetType) {
	*arg = &val
}

type ValidationErrorFieldGetReasonArgType = string
type ValidationErrorFieldGetReasonRetType = string

// ValidationErrorField struct for ValidationErrorField
type ValidationErrorField struct {
	// The name of the field in the request that has failed the validation
	// REQUIRED
	Field ValidationErrorFieldGetFieldAttributeType `json:"field" required:"true"`
	// The reason why the validation failed
	// REQUIRED
	Reason ValidationErrorFieldGetReasonAttributeType `json:"reason" required:"true"`
}

type _ValidationErrorField ValidationErrorField

// NewValidationErrorField instantiates a new ValidationErrorField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorField(field ValidationErrorFieldGetFieldArgType, reason ValidationErrorFieldGetReasonArgType) *ValidationErrorField {
	this := ValidationErrorField{}
	setValidationErrorFieldGetFieldAttributeType(&this.Field, field)
	setValidationErrorFieldGetReasonAttributeType(&this.Reason, reason)
	return &this
}

// NewValidationErrorFieldWithDefaults instantiates a new ValidationErrorField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorFieldWithDefaults() *ValidationErrorField {
	this := ValidationErrorField{}
	return &this
}

// GetField returns the Field field value
func (o *ValidationErrorField) GetField() (ret ValidationErrorFieldGetFieldRetType) {
	ret, _ = o.GetFieldOk()
	return ret
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorField) GetFieldOk() (ret ValidationErrorFieldGetFieldRetType, ok bool) {
	return getValidationErrorFieldGetFieldAttributeTypeOk(o.Field)
}

// SetField sets field value
func (o *ValidationErrorField) SetField(v ValidationErrorFieldGetFieldRetType) {
	setValidationErrorFieldGetFieldAttributeType(&o.Field, v)
}

// GetReason returns the Reason field value
func (o *ValidationErrorField) GetReason() (ret ValidationErrorFieldGetReasonRetType) {
	ret, _ = o.GetReasonOk()
	return ret
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorField) GetReasonOk() (ret ValidationErrorFieldGetReasonRetType, ok bool) {
	return getValidationErrorFieldGetReasonAttributeTypeOk(o.Reason)
}

// SetReason sets field value
func (o *ValidationErrorField) SetReason(v ValidationErrorFieldGetReasonRetType) {
	setValidationErrorFieldGetReasonAttributeType(&o.Reason, v)
}

func (o ValidationErrorField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getValidationErrorFieldGetFieldAttributeTypeOk(o.Field); ok {
		toSerialize["Field"] = val
	}
	if val, ok := getValidationErrorFieldGetReasonAttributeTypeOk(o.Reason); ok {
		toSerialize["Reason"] = val
	}
	return toSerialize, nil
}

type NullableValidationErrorField struct {
	value *ValidationErrorField
	isSet bool
}

func (v NullableValidationErrorField) Get() *ValidationErrorField {
	return v.value
}

func (v *NullableValidationErrorField) Set(val *ValidationErrorField) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorField) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorField(val *ValidationErrorField) *NullableValidationErrorField {
	return &NullableValidationErrorField{value: val, isSet: true}
}

func (v NullableValidationErrorField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
